import { createHmac } from 'node:crypto';

/**
 * RFC 6238 TOTP code generation for the harness (TS-505d1).
 *
 * **Why the suite implements this rather than importing the service's.**
 * `service-identity`'s `TotpService` exports its primitives as `_internals`
 * for its own unit tests, and reaching for them here would be a shorter file.
 * It would also make the assertion worthless: a code generated by the same
 * implementation that verifies it agrees with itself no matter how wrong both
 * are. The suite's job is to be the authenticator app, which is a genuinely
 * separate implementation of a published standard — so this is written from
 * RFC 4226 §5.3 (dynamic truncation) and RFC 6238 §4 (the step counter) with
 * no reference to the server's code, and `POST /auth/mfa/totp/confirm`
 * accepting the result is the cross-check.
 *
 * Pinned to the parameters `service-identity` puts in its `otpauth://` URL and
 * the contract enforces: HMAC-SHA-1, 6 digits, 30-second period. They are
 * arguments with defaults rather than constants so a spec that changes
 * `MFA_TOTP_PERIOD_SECONDS` on a fleet member can say so out loud.
 *
 * Nothing here is a security control — it is the client half of a protocol,
 * running against a throwaway database with a secret the same process just
 * minted. Constant-time comparison, replay watermarks and secret storage are
 * the server's concerns and are covered by its own suite.
 */

export const TOTP_DEFAULT_DIGITS = 6;
export const TOTP_DEFAULT_PERIOD_SECONDS = 30;

export interface TotpOptions {
  readonly digits?: number;
  readonly periodSeconds?: number;
  /** Overrides "now". Used to prove a stale code is rejected. */
  readonly at?: Date;
}

/**
 * The current 6-digit code for a base32 shared secret.
 *
 * `secretBase32` is the value `POST /auth/mfa/totp/enroll` returns — the same
 * string a user would paste into a desktop authenticator.
 */
export function totpCode(secretBase32: string, options: TotpOptions = {}): string {
  const periodSeconds = options.periodSeconds ?? TOTP_DEFAULT_PERIOD_SECONDS;
  const at = options.at ?? new Date();
  const step = Math.floor(at.getTime() / 1000 / periodSeconds);
  return codeForStep(base32Decode(secretBase32), step, options.digits ?? TOTP_DEFAULT_DIGITS);
}

/**
 * Seconds remaining in the current TOTP step.
 *
 * Enrolment and login each spend a code, and the server's replay guard rejects
 * a step it has already accepted (`mfa_methods.last_used_step`). Two calls
 * inside one 30-second window therefore present the *same* code and the second
 * is refused — a failure that reads as "MFA is broken" rather than "the suite
 * was fast". Callers wait out the boundary rather than retrying, so the wait
 * is bounded and stated (the suite's rule: no `sleep()` as a fudge, but an
 * explicit wait for a protocol-defined window is not a fudge).
 */
export function secondsUntilNextStep(
  options: Pick<TotpOptions, 'periodSeconds' | 'at'> = {},
): number {
  const periodSeconds = options.periodSeconds ?? TOTP_DEFAULT_PERIOD_SECONDS;
  const at = options.at ?? new Date();
  const seconds = at.getTime() / 1000;
  return periodSeconds - (seconds % periodSeconds);
}

/**
 * RFC 4226 §5.3 — HMAC-SHA-1 over the 8-byte big-endian counter, dynamically
 * truncated to a 31-bit integer, modulo 10^digits, zero-padded.
 */
function codeForStep(secret: Buffer, step: number, digits: number): string {
  const counter = Buffer.alloc(8);
  counter.writeBigInt64BE(BigInt(step), 0);

  const digest = createHmac('sha1', secret).update(counter).digest();

  const offset = digest[digest.length - 1]! & 0x0f;
  const truncated =
    ((digest[offset]! & 0x7f) << 24) |
    ((digest[offset + 1]! & 0xff) << 16) |
    ((digest[offset + 2]! & 0xff) << 8) |
    (digest[offset + 3]! & 0xff);

  return (truncated % 10 ** digits).toString().padStart(digits, '0');
}

/**
 * RFC 4648 §6 base32 decode. Case-insensitive, tolerant of the padding and
 * spacing authenticator apps display, and loud on anything outside the
 * alphabet — a silently-mangled secret would surface as an unexplainable 401
 * at verify time.
 */
function base32Decode(input: string): Buffer {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  const cleaned = input.toUpperCase().replace(/[\s=]/g, '');
  let bits = 0;
  let value = 0;
  const bytes: number[] = [];

  for (let index = 0; index < cleaned.length; index++) {
    const character = cleaned[index]!;
    const position = alphabet.indexOf(character);
    if (position < 0) {
      throw new Error(
        `TOTP secret is not valid base32: unexpected '${character}' at offset ${String(index)}`,
      );
    }
    value = (value << 5) | position;
    bits += 5;
    if (bits >= 8) {
      bytes.push((value >>> (bits - 8)) & 0xff);
      bits -= 8;
    }
  }

  if (bytes.length === 0) {
    throw new Error('TOTP secret decoded to zero bytes');
  }
  return Buffer.from(bytes);
}
